# Configuration file for create_ms.py and generate.py

# Settings for simms to generate a new empty measurement set.
create_ms:
  msname: 'datasets/ms/KAT7_200_7_1.MS' 
  tel: 'kat-7'
  pos_type: 'ascii'
  pos: 'datasets/antenna_tables/kat-7.itrf.txt'
  dec: ' -30d0m0s' 
  ra: '0h0m0s'    
  synthesis: 5
  dtime: 90
  freq0: "1.4GHz" #1.4GHz
  nchan: "1"
  dfreq: "10MHz"
  stokes: "RR RL LR LL"
  

# Settings for generate.py to produce gains, model and vis data
# with a given ms.
generate:
  ms: 'datasets/ms/KAT7_200_7_1.MS'
  mode: 'normal'
  sky_model: 'datasets/sky_models/MODEL-1.txt'
  utimes_per_chunk: 1
  ncpu: 8
  alpha_std: 0.1
  sigma_n: 0.1
  lt: 0.05
  lnu: 0.05
  ls: 0.5
  sigma_f: 1.0
  phase_convention: "CODEX"
  out: ""