name: kal-cal

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04
    if: 
      "contains(github.event.head_commit.message, '[build]')"
    strategy:
      matrix:
        python-version: [3.6]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test with pytest
      run: |
        NCPU=$(nproc --all)
        pytest -n $NCPU tests/